# Generated by Django 4.1.3 on 2023-05-29 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='dashboard.drug'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='dashboard.stock'),
        ),
    ]
