# Generated by Django 4.2.1 on 2023-05-30 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_sale_drug_selling_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='selling_price',
            field=models.PositiveIntegerField(),
        ),
        migrations.RenameModel(
            old_name='Sale',
            new_name='Invoice',
        ),
        migrations.CreateModel(
            name='SalesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_items', to='dashboard.drug')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_items', to='dashboard.invoice')),
            ],
        ),
    ]
