# Generated by Django 4.2.1 on 2023-06-27 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_productcategories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategories',
            new_name='ProductCategory',
        ),
    ]
