# Generated by Django 4.2.2 on 2023-07-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_diagnosis_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='unit_name_plural',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
