# Generated by Django 4.2.2 on 2023-07-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_drug_unit_name_plural'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='unit_name_plural',
            field=models.CharField(default='', max_length=20),
        ),
    ]
